fix: use BigInt for fixed columns
Fixed columns can contain a number in the field, which would not fit
u64. A concrete example is the newly added circuit simple/mul.rs,
which has a fixed column that contains the field order minus one (-1).
Prior this commit, running the test would result in the following error:

---- test::integration_tests_zcash::tests::simple_test stdout ----
thread 'test::integration_tests_zcash::tests::simple_test' panicked at korrekt/src/circuit_analyzer/analyzer.rs:108:26:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }

This commit fixes the issue by switching from u64 to BigInt.